# Pre-commit configuration for giantcroissant-lunar-dev-rule repository
# This is MINIMAL config for developing the rule system itself
# (The full template configs are in templates/hooks/)

repos:
  # Basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            .*\.md  # Preserve markdown trailing spaces
          )$
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^templates/  # Don't validate template files (they're examples)
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Secret detection (critical for a public repo)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # Shell script linting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        files: \.sh$
        args: ['--severity=warning']

  # Markdown linting (relaxed for documentation)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ['--fix', '--disable', 'MD013', 'MD033', 'MD041']
        # MD013: Line length (too restrictive for docs)
        # MD033: Inline HTML (useful in markdown)
        # MD041: First line must be H1 (not always needed)

  # Python linting (for validator scripts in templates/)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        files: ^templates/hooks/python/.*\.py$
      - id: ruff-format
        files: ^templates/hooks/python/.*\.py$

# Configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0
